// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5283_g7yXoUi_8FeJN5JOeQjpdvZMg18',
    appId: '1:786618844707:web:a104de7460be24c4e9d396',
    messagingSenderId: '786618844707',
    projectId: 'ecommerceproject-14a71',
    authDomain: 'ecommerceproject-14a71.firebaseapp.com',
    storageBucket: 'ecommerceproject-14a71.appspot.com',
    measurementId: 'G-WZ00WL6QZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBam_0kJ5QD6RSkBUtt7QlunN85wBx9j6M',
    appId: '1:786618844707:android:b0f7c87aca5b6b8ce9d396',
    messagingSenderId: '786618844707',
    projectId: 'ecommerceproject-14a71',
    storageBucket: 'ecommerceproject-14a71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIPEK7G-9Pd8Pb6JETsKrufPcu5g5mWBM',
    appId: '1:786618844707:ios:f07fd7cc59c1276ae9d396',
    messagingSenderId: '786618844707',
    projectId: 'ecommerceproject-14a71',
    storageBucket: 'ecommerceproject-14a71.appspot.com',
    androidClientId: '786618844707-1qi54q9urqcmpug44184hobvn3fjrleo.apps.googleusercontent.com',
    iosClientId: '786618844707-0pegd2o5rs6mglhvb10beus2m2h7i9ha.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );
}
