// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDz_JuOulN8NQL0OhwDet5lpNgGsXKJltI',
//     appId: '1:1031168110972:web:c8eecc35f4e866f705f4f9',
//     messagingSenderId: '1031168110972',
//     projectId: 'appdev-ba88d',
//     authDomain: 'appdev-ba88d.firebaseapp.com',
//     storageBucket: 'appdev-ba88d.appspot.com',
//     measurementId: 'G-P52QFCKQRL',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyC3Wc7k4ydAOAvUJpauSov32ZIIhr5kCp0',
//     appId: '1:1031168110972:android:dd3b9dcd10cad1bd05f4f9',
//     messagingSenderId: '1031168110972',
//     projectId: 'appdev-ba88d',
//     storageBucket: 'appdev-ba88d.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyC2FeX8tR3KyjwGFd-DyPdY0ZtVM61sfi4',
//     appId: '1:1031168110972:ios:ccee2efab80666d605f4f9',
//     messagingSenderId: '1031168110972',
//     projectId: 'appdev-ba88d',
//     storageBucket: 'appdev-ba88d.appspot.com',
//     iosBundleId: 'com.example.tStore',
//   );
// }
